### PR TITLE
securing the host database

### PR DESCRIPTION
**Pull request by mainboarder**
Proposal for https://github.com/haiwen/seafile-admin-docs/issues/113

### CODE REVIEW

**Comment by dimejo** [comment]
Are you sure that this is necessary? In my setup I'm using the service name in `docker-compose.yml` for name resolution.
**[docker-compose.yml](https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml):**
```
version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net
```
In the example above 'db' is used as service name thus you can use `host = db` in `ccnet.conf` and `seafile.conf`.

As the mysql service doesn't expose any ports all communication happens over an isolated network.

**Comment by mainboarder** [comment]
When using mariadb in a container everything is fine.
But when using mariadb from the host, than you probably have this problem.

**Comment by dimejo** [comment]
Makes sense. I wasn't reading the docs article, just your PR.

**Comment by freeplant** [comment]
Thanks.

**Pull request merged**
